//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewHouse.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string customerid { get; set; }
        public string customer_name { get; set; }
        public string customer_city { get; set; }
        public Nullable<int> customer_mobile { get; set; }
        public string customer_email { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
